package com.thesispr.BusReservationSystem.model;

import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Represents a reservation made by a user for a specific bus line.
 */
@Entity
public class Reservation {

    /**
     * The unique identifier for the reservation.
     * Automatically generated by the database upon insertion of a new record.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The date of the reservation. */
    private LocalDate reservation_date;

    /** The time of the reservation. */
    private LocalTime reservation_time;

    /** The name of the bus line for the reservation. */
    private String bus_line;

    /** The username associated with the reservation. */
    private String user;

    /** The seat number of the reservation. */
    private int seat_number;

    /** The price of the reservation. */
    private int price;

    /** The username associated with the reservation. */
    private String username;

    /** The selected seats for the reservation. */
    private String selected_seats;

    /**
     * Gets the unique identifier of the reservation.
     * @return The reservation ID.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the reservation.
     * @param id The reservation ID.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the date of the reservation.
     * @return The date of the reservation.
     */
    public LocalDate getReservation_date() {
        return reservation_date;
    }

    /**
     * Sets the date of the reservation.
     * @param reservation_date The date of the reservation.
     */
    public void setReservation_date(LocalDate reservation_date) {
        this.reservation_date = reservation_date;
    }

    /**
     * Gets the time of the reservation.
     * @return The time of the reservation.
     */
    public LocalTime getReservation_time() {
        return reservation_time;
    }

    /**
     * Sets the time of the reservation.
     * @param reservation_time The time of the reservation.
     */
    public void setReservation_time(LocalTime reservation_time) {
        this.reservation_time = reservation_time;
    }

    /**
     * Gets the seat number of the reservation.
     * @return The seat number of the reservation.
     */
    public int getSeat_number() {
        return seat_number;
    }

    /**
     * Sets the seat number of the reservation.
     * @param seat_number The seat number of the reservation.
     */
    public void setSeat_number(int seat_number) {
        this.seat_number = seat_number;
    }

    /**
     * Gets the price of the reservation.
     * @return The price of the reservation.
     */
    public int getPrice() {
        return price;
    }

    /**
     * Sets the price of the reservation.
     * @param price The price of the reservation.
     */
    public void setPrice(int price) {
        this.price = price;
    }

    /**
     * Gets the name of the bus line for the reservation.
     * @return The name of the bus line.
     */
    public String getBus_line() {
        return bus_line;
    }

    /**
     * Sets the name of the bus line for the reservation.
     * @param bus_line The name of the bus line.
     */
    public void setBus_line(String bus_line) {
        this.bus_line = bus_line;
    }

    /**
     * Gets the username associated with the reservation.
     * @return The username associated with the reservation.
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the username associated with the reservation.
     * @param user The username associated with the reservation.
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * Gets the selected seats for the reservation.
     * @return The selected seats for the reservation.
     */
    public String getSelected_seats() {
        return selected_seats;
    }

    /**
     * Sets the selected seats for the reservation.
     * @param selected_seats The selected seats for the reservation.
     */
    public void setSelected_seats(String selected_seats) {
        this.selected_seats = selected_seats;
    }

    /**
     * Gets the username associated with the reservation.
     * @return The username associated with the reservation.
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username associated with the reservation.
     * @param username The username associated with the reservation.
     */
    public void setUsername(String username) {
        this.username = username;
    }
}
